services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=app.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
